project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality_control/', include('quality_control.urls')), 
    path('', include('tasks.urls')),
]

project_tracker/quality_control/urls.py
from django.urls import path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    path('', views.index, name='index'),
    path('bugs/', views.bug_list, name='bug_list'), 
	path('bug_detail/<int:bug_id>', views.bug_detail, name='bug_detail'), 
    path('features/', views.feature_list, name='feature_list'),
    path('feature_id_detail/<int:feature_id>', views.feature_id_detail, name='feature_id_detail'), 
    
    # path('', views.IndexView.as_view(), name='index'),
    # path('bug_detail/<int:bug_id>', views.BugReportDetailView.as_view(), name='bug_detail'), 
    # path('feature_id_detail/<int:feature_id>', views.FeatureRequestDetailView.as_view(), name='feature_id_detail'), 
]

project_tracker/tasks/urls.py
from django.urls import path, include
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('quality_control/', include('quality_control.urls')),  
    # path('projects/', views.projects_list, name='projects_list'),
    # path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    
    # path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
]

project_tracker/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <!-- Общий заголовок для всех страниц -->
      <h1>Проект project-tracker</h1>
    </header>
    {% include 'base/nav.html' %}
    <main>
        {% block content %}
        <!-- Основное содержимое страницы -->
        {% endblock %}
    </main>

    <footer>
        <!-- Общий футер для всех страниц -->
    </footer>
</body>
</html>

project_tracker/templates/base/nav.html
<nav>
    <!-- Навигационное меню -->
    <a href="{% url 'tasks:index' %}">Приложение tasks</a>
    <br>
    <a href="{% url 'quality_control:index' %}">Приложение quality_control</a>
    <!-- Другие ссылки -->
</nav>