project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality_control/', include('quality_control.urls')), 
    path('', include('tasks.urls')),
]

project_tracker/quality_control/urls.py
from django.urls import path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    path('', views.index, name='index'),
    path('bugs/', views.bug_list, name='bug_list'), 
	path('bug_detail/<int:bug_id>', views.bug_detail, name='bug_detail'), 
    path('features/', views.feature_list, name='feature_list'),
    path('feature_id_detail/<int:feature_id>', views.feature_id_detail, name='feature_id_detail'), 
    
    # path('', views.IndexView.as_view(), name='index'),
    # path('bug_detail/<int:bug_id>', views.BugReportDetailView.as_view(), name='bug_detail'), 
    # path('feature_id_detail/<int:feature_id>', views.FeatureRequestDetailView.as_view(), name='feature_id_detail'), 
]

project_tracker/tasks/urls.py
from django.urls import path, include
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('quality_control/', include('quality_control.urls')),  
    # path('projects/', views.projects_list, name='projects_list'),
    # path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    
    # path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
]

project_tracker/quality_control/models.py
from django.db import models
from tasks.models import Project, Task
from django.core.validators import MaxValueValidator, MinValueValidator

class BugReport(models.Model):
	def __str__(self):
		return self.title

	project = models.ForeignKey(
		Project,
		related_name='BugReport',
		on_delete=models.CASCADE
	)
	title = models.CharField(max_length=100)
	description = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
 
	STATUS_BUGS = [
        ('Consideration', 'Рассмотрение'),
        ('Accepted', 'Принято'),
        ('Rejected', 'Отклонено'),
    ]
	status = models.CharField(
        max_length=50,
        choices=STATUS_BUGS,
        default='New',
    )
	priority = models.IntegerField(
     	default=1,
		validators=[
			MinValueValidator(1),
			MaxValueValidator(5)
		]
    )
	
class FeatureRequest(models.Model):
	def __str__(self):
		return self.title

	project = models.ForeignKey(
		Project,
		related_name='FeatureRequest',
		on_delete=models.CASCADE
	)
	title = models.CharField(max_length=100)
	description = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
 
	STATUS_BUGS = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена'),
    ]
	status = models.CharField(
        max_length=50,
        choices=STATUS_BUGS,
        default='New',
    )
	priority = models.IntegerField(
     	default=1,
		validators=[
			MinValueValidator(1),
			MaxValueValidator(5)
		]
    )

project_tracker/quality_control/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.views import View
from .models import BugReport, FeatureRequest
from django.views.generic import DetailView
from django.shortcuts import render
from django.shortcuts import get_object_or_404
    
class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')

def index(request):
    return render(request, 'quality_control/index.html')

def bug_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bug_list.html', {'bugs': bugs})

class BugReportDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bug_detail.html'
    
class FeatureRequestDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    template_name = 'quality_control/feature_detail.html'
    
def bug_detail(request, bug_id):
    bug = get_object_or_404(BugReport, id=bug_id)
    return render(request, 'quality_control/bug_detail.html', {'bug': bug})

def feature_id_detail(request, feature_id):
    feature = get_object_or_404(FeatureRequest, id=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'feature': feature})

def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'features': features})

project_tracker/quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block content %}
	<h1>{{ bug.title }}</h1>
	<p>{{ bug.description }}</p>

	<li>Status: {{bug.status}}</li><li>Priority: {{bug.priority}}</li>
	<li>Task's name: <b>{{bug.task.name}}</b></li><li>Project's name: <b>{{bug.project.name}}</li>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список всех BugReport</h1><ul>
    <ul>
        {% for bug in bugs %}
			<li><a href="{% url 'quality_control:bug_detail' bug.id %}">{{ bug.title }}</a><br>Status: {{ bug.status }}<br></li>
        {% endfor %}
    </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
	<h1>{{ feature.title }}</h1>
	<p>{{ feature.description }}</p>

	<li>Status: {{feature.status}}</li><li>Priority: {{feature.priority}}</li>
	<li>Task's name: <b>{{feature.task.name}}</b></li><li>Project's name: <b>{{feature.project.name}}</li>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список всех BugReport</h1>
    <ul>
        {% for feature in features %}
			<li><a href="{% url 'quality_control:feature_id_detail' feature.id %}">{{ feature.title }}</a><br>Status: {{ feature.status }}<br></li>
        {% endfor %}
    </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
		<h1>Система контроля качества</h1>
		<a href="{% url 'quality_control:bug_list' %}"><h2>Список всех багов</h2></a>
		<h2><a href="{% url 'quality_control:feature_list' %}">Запросы на улучшение</a></h2>
{% endblock %}